### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by Amrutha1101** [ashutoshkrris/iRead#12]
### Is your feature request related to a problem? Please describe.
As the website doesn't contain scrolling bar. I would like to add one

### Which Program are you part of?

- [x] DCP21

**Comment by harshita9621** [comment]
Can I work on this issue

**Comment by ashutoshkrris** [comment]
@Amrutha1101 assigning it to you!
@harshita9621 since, @Amrutha1101 created the issue and asked to work on it first, I have to assign her. In any condition, she fails to do it, you will be assigned.

**Comment by Amrutha1101** [comment]
@harshita9621 you can go ahead as I will not be able to solve this issue.

**Comment by ashutoshkrris** [comment]
@harshita9621 would you like to work?

**Comment by harshita9621** [comment]
Yes

**Comment by ashutoshkrris** [comment]
Alright @harshita9621 
Assigning it to you..

**Comment by purohitmansi** [comment]
Please do assign this to me.

**Comment by ashutoshkrris** [comment]
Hey @purohitmansi 
Harshita is currently working on this issue. If she is not able to do it, I'll assign it to you

**Comment by purohitmansi** [comment]
Okay

**Comment by harshita9621** [comment]
@ashutoshkrris I will not be able to solve this issue.

**Comment by ashutoshkrris** [comment]
No problem @harshita9621 
@purohitmansi  let me know, if you would like to work

**Comment by purohitmansi** [comment]
Yes, I want to.

**Comment by ashutoshkrris** [comment]
Sure @purohitmansi 
Assigning it to you

**Comment by ashutoshkrris** [comment]
@purohitmansi any update?

**Comment by purohitmansi** [comment]
I am not able to.Go ahead

**Comment by mayank-wadhwa-git** [comment]
i would like to try it. Please assign it to me

**Comment by ashutoshkrris** [comment]
Go ahead @mayank-wadhwa-git !
