### ISSUE TITLE
Add a Contributors Section

### ISSUE THREAD

**Issue by Prakash-Haldar** [ashutoshkrris/iRead#13]
A Contributors section in Readme which shows the name & profile pic of contributors of this project @ashutoshkrris

**Comment by ashutoshkrris** [comment]
Sure @Prakash-Haldar 
Go ahead!

**Comment by ashutoshkrris** [comment]
Hey @Prakash-Haldar 
I think, there should only be their profile pictures and that should be linked with their Github profiles.

How about it?

**Comment by Prakash-Haldar** [comment]
Yess it will be like that

**Comment by Prakash-Haldar** [comment]
I have created the pull request , Please see to it.
