### ISSUE TITLE
Modifying the header

### ISSUE THREAD

**Issue by 2024-SANDHYA** [ashutoshkrris/iRead#17]
Want to modify the header of the website especially the icons. @ashutoshkrris

**Comment by ashutoshkrris** [comment]
Hey @2024-SANDHYA 
Could you show some samples?

**Comment by 2024-SANDHYA** [comment]
> 
> 
> Hey @2024-SANDHYA
> Could you show some samples?

Samples as in ?

**Comment by ashutoshkrris** [comment]
@2024-SANDHYA 
I meant, how would you like to change the header?
And what icons would you change?

**Comment by 2024-SANDHYA** [comment]
> 
> 
> @2024-SANDHYA
> I meant, how would you like to change the header?
> And what icons would you change?

I want to add some zoom hover effects on the icons , will not delete or add any new one.

**Comment by ashutoshkrris** [comment]
Alright @2024-SANDHYA
Assigning it to you..
